### ISSUE TITLE
How to set the device protocols information

### ISSUE THREAD

**Issue by kason-huang** [openyurtio/yurt-device-controller#10]
I want to know how to set the device protocols in the device-service? For example, if I want to set the modubs-tcp or modbus-rtu prtocols in device-service [link](https://github.com/edgexfoundry/device-modbus-go/blob/main/cmd/res/devices/modbus.test.devices.toml#L8), what should I do ?

**Comment by khalid-jobs** [comment]
I want to know how the device-service fetch the device file (such as "devices.toml"). And I am a little confused about the relations of addressable filed in 
```
apiVersion: device.openyurt.io/v1alpha1
kind: DeviceService
metadata:
  name: hangzhou-device-service-test
spec:
  nodePool: hangzhou
  addressable:
    address: edgex-device-virtual-test
    method: POST
    name: device-service-test
    path: /api/v1/callback
    port: 49999
    protocol: HTTP
  adminState: UNLOCKED
  operatingState: ENABLED
```
and [DeviceList.protocol](https://github.com/edgexfoundry/device-modbus-go/blob/main/cmd/res/devices/modbus.test.devices.toml#L8)
