### ISSUE TITLE
[BUG] device cr repeated when create device from k8s

### ISSUE THREAD

**Issue by theonefx** [openyurtio/yurt-device-controller#47]
If i create a new device from k8s as yaml below:
```yaml
apiVersion: "device.openyurt.io/v1alpha1"
kind: "Device"
metadata:
  labels:
    device-controller/edgex-object.name: "d1"
  name: "np7800702af3f84b8793731d53c49d96c9-d1"
  namespace: "edge-paas-edge"
spec:
  description: "d1"
  adminState: "UNLOCKED"
  operatingState: "UP"
  protocols:
    mqtt: {}
  labels: []
  location: "??"
  serviceName: "device-virtual"
  profileName: "Random-Float-Device"
  notify: false
  managed: true
  nodePool: "np7800702af3f84b8793731d53c49d96c9"
  deviceProperties: {}
```

then, device-controller will create two device with name:
- np7800702af3f84b8793731d53c49d96c9-d1
- np7800702af3f84b8793731d53c49d96c9-np7800702af3f84b8793731d53c49d96c9-d1

**Environment**:
- OpenYurt version: 
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**

/kind bug
